"""Reference data for the variant tests, from Fairy-Stockfish (pip install pyffish).

Writes src/test/resources/variants/oracle.txt: for each built-in variant, seeded random games
with the sorted legal moves Fairy-Stockfish gives at every ply, and perft counts from a few
positions. The Java tests (ai.variant.VariantOracleTest) read it; they never run Python.

    python3 tools/variant_oracle.py
"""
import random
import pyffish as sf

# our variant id -> Fairy-Stockfish's name
VARIANTS = {"chess": "chess", "antichess": "antichess", "king-of-the-hill": "kingofthehill",
            "three-check": "3check"}
GAMES = 6
PLIES = 120
PERFT_DEPTH = 3
OUT = "src/test/resources/variants/oracle.txt"


def perft(variant, fen, depth):
    if depth == 0:
        return 1
    moves = sf.legal_moves(variant, fen, [])
    if depth == 1:
        return len(moves)
    return sum(perft(variant, sf.get_fen(variant, fen, [m]), depth - 1) for m in moves)


def main():
    rnd = random.Random(2026)
    lines = ["# Generated by tools/variant_oracle.py from Fairy-Stockfish " + ".".join(map(str, sf.version())),
             "# moves | <variant> | <fen> | <sorted legal moves, space separated>",
             "# perft | <variant> | <fen> | <depth> | <count>",
             "# san   | <variant> | <fen> | <uci> | <SAN of the move played>",
             "# end   | <variant> | <fen> | <win, loss or draw for the side to move>"]
    for ours, fairy in VARIANTS.items():
        perft_fens = [sf.start_fen(fairy)]
        for game in range(GAMES):
            fen = sf.start_fen(fairy)
            for ply in range(PLIES):
                moves = sorted(sf.legal_moves(fairy, fen, []))
                lines.append(f"moves | {ours} | {fen} | {' '.join(moves)}")
                if not moves:
                    value = sf.game_result(fairy, fen, [])
                    lines.append(f"end | {ours} | {fen} | {'win' if value > 0 else 'loss' if value < 0 else 'draw'}")
                    break
                if ply in (15, 40) and game < 3:
                    perft_fens.append(fen)
                move = rnd.choice(moves)
                lines.append(f"san | {ours} | {fen} | {move} | {sf.get_san(fairy, fen, move)}")
                fen = sf.get_fen(fairy, fen, [move])
        for fen in perft_fens:
            for depth in range(1, PERFT_DEPTH + 1):
                lines.append(f"perft | {ours} | {fen} | {depth} | {perft(fairy, fen, depth)}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
