"""Reference data for the variant tests, from Fairy-Stockfish (pip install pyffish).

Writes src/test/resources/variants/oracle.txt: for each built-in variant, seeded random games
with the sorted legal moves Fairy-Stockfish gives at every ply, and perft counts from a few
positions. Then the same for the made-up variants in src/test/resources/variants/made/*.json
(Phase 6 R5): their invented pieces go to Fairy-Stockfish as the Betza text our own writer put in
the file, so the parser, the writer and the move generator are all checked against it.
The Java tests (ai.board.VariantOracleTest) read it; they never run Python.

    python3 tools/variant_oracle.py
"""
import glob
import json
import os
import random
import pyffish as sf

# our variant id -> Fairy-Stockfish's name
VARIANTS = {"chess": "chess", "antichess": "antichess", "king-of-the-hill": "kingofthehill",
            "three-check": "3check"}
GAMES = 6
PLIES = 120
PERFT_DEPTH = 3
OUT = "src/test/resources/variants/oracle.txt"
MADE = "src/test/resources/variants/made"

# chess pieces Fairy-Stockfish has built in: letter -> (its name in a config, our Betza for it)
BUILT_IN = {"Q": ("queen", "RB"), "R": ("rook", "R"), "B": ("bishop", "B"), "N": ("knight", "N")}


def perft(variant, fen, depth):
    if depth == 0:
        return 1
    moves = sf.legal_moves(variant, fen, [])
    if depth == 1:
        return len(moves)
    return sum(perft(variant, sf.get_fen(variant, fen, [m]), depth - 1) for m in moves)


def made_config(variant):
    """A Fairy-Stockfish config section for one of our made variants (chess or antichess base)."""
    # old files say "goal"; newer ones list "goals" (docs/variant-rules.md)
    kinds = [g["kind"] for g in variant["goals"]] if "goals" in variant else [variant["goal"]]
    base = "antichess" if "LOSE_EVERYTHING" in kinds else "chess"
    lines = [f"[{variant['id']}:{base}]"]
    letters = {p["letter"]: p for p in variant["pieces"]}
    for letter, (name, betza) in BUILT_IN.items():
        if letters.get(letter, {}).get("betza") != betza:
            lines.append(f"{name} = -")
    custom = 0
    for p in variant["pieces"]:
        letter = p["letter"]
        if letter in ("K", "P"):
            continue  # king and pawn stay Fairy-Stockfish's own; the test files use the standard ones
        if BUILT_IN.get(letter, (None, None))[1] == p["betza"]:
            continue
        custom += 1
        lines.append(f"customPiece{custom} = {letter.lower()}:{p['betza']}")
    pawn = letters["P"]
    lines.append(f"promotionPieceTypes = {pawn['promotesTo'].lower()}")
    lines.append(f"castling = {'true' if variant['castling'] else 'false'}")
    lines.append(f"startFen = {variant['start']}")
    return "\n".join(lines) + "\n"


def made_variants():
    """Our id -> Fairy-Stockfish's name for each made variant, loaded into Fairy-Stockfish."""
    out = {}
    for path in sorted(glob.glob(os.path.join(MADE, "*.json"))):
        with open(path) as f:
            variant = json.load(f)
        sf.load_variant_config(made_config(variant))
        out[variant["id"]] = variant["id"]
    return out


def main():
    rnd = random.Random(2026)
    lines = ["# Generated by tools/variant_oracle.py from Fairy-Stockfish " + ".".join(map(str, sf.version())),
             "# moves | <variant> | <fen> | <sorted legal moves, space separated>",
             "# perft | <variant> | <fen> | <depth> | <count>",
             "# san   | <variant> | <fen> | <uci> | <SAN of the move played>",
             "# end   | <variant> | <fen> | <win, loss or draw for the side to move>"]
    for ours, fairy in {**VARIANTS, **made_variants()}.items():
        perft_fens = [sf.start_fen(fairy)]
        for game in range(GAMES):
            fen = sf.start_fen(fairy)
            for ply in range(PLIES):
                moves = sorted(sf.legal_moves(fairy, fen, []))
                lines.append(f"moves | {ours} | {fen} | {' '.join(moves)}")
                if not moves:
                    value = sf.game_result(fairy, fen, [])
                    lines.append(f"end | {ours} | {fen} | {'win' if value > 0 else 'loss' if value < 0 else 'draw'}")
                    break
                if ply in (15, 40) and game < 3:
                    perft_fens.append(fen)
                move = rnd.choice(moves)
                lines.append(f"san | {ours} | {fen} | {move} | {sf.get_san(fairy, fen, move)}")
                fen = sf.get_fen(fairy, fen, [move])
        for fen in perft_fens:
            for depth in range(1, PERFT_DEPTH + 1):
                lines.append(f"perft | {ours} | {fen} | {depth} | {perft(fairy, fen, depth)}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
